version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs

  wiki:
    image: uffizziqa.azurecr.io/example-wiki:latest
    environment:
      DB_TYPE: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki

ingress:
  service: wiki
  port: 3000

continuous_preview:
  deploy_preview_when_image_tag_is_created: true
  share_to_github: true
