orbs:
  azure-acr: circleci/azure-acr@0.2.0
version: 2.1 # Use version 2.1 config to get access to orbs, pipelines

workflows:
  build-push-azure:
    jobs:
      - azure-acr/build-and-push-image:
          name: Build Image from Pull Request and Push to Azure Container Registry
          filters:
            branches:
              ignore: dev
          pre-steps:
            - run:
                name: Setup Environment Variables For Pull Request
                command: echo 'export TAG=uffizzi_request_`echo $CIRCLE_PULL_REQUEST | grep [^\/]*$ --only-matching`' >> $BASH_ENV
            - run:
                name: (Echo $TAG for Troubleshooting)
                command: echo $TAG
          dockerfile: # defaults to `Dockerfile`
          path: # Defaults to working directory
          login-server-name: uffizziqa.azurecr.io # e.g. {yourregistryname}.azure.io
          registry-name: uffizziqa
          repo: example-wiki
          tag: $TAG
          context:
            - test-acr-service-principal

      - azure-acr/build-and-push-image:
          name: Build Image from `dev` Branch and Push to Azure Container Registry
          filters:
            branches:
              only: dev
          dockerfile: # defaults to `Dockerfile`
          path: # Defaults to working directory
          login-server-name: uffizziqa.azurecr.io # e.g. {yourregistryname}.azure.io
          registry-name: uffizziqa
          repo: example-wiki
          tag: latest
          context:
            - test-acr-service-principal

      - azure-acr/build-and-push-image:
          name: Build Image from Tag and Push to Azure Container Registry
          filters:
            tags: 
              only: /.*/
            branches:
              ignore: /.*/
          dockerfile: # defaults to `Dockerfile`
          path: # Defaults to working directory
          login-server-name: uffizziqa.azurecr.io # e.g. {yourregistryname}.azure.io
          registry-name: uffizziqa
          repo: example-wiki
          tag: $CIRCLE_TAG
          context:
            - test-acr-service-principal
